name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Load fuse
      run: modprobe fuse && apt install libfuse2
      
    - uses: actions/checkout@v3

    - name: Build
      run: make build
    
    - name: Upload a AppImage Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: HeidiSQL.AppImage
        path: HeidiSQL.AppImage
